// Shared contracts between the Tool Registry, Tool Executor, and individual tool definitions.
import type { z } from "zod";
import type { FunctionTool } from "openai/resources/responses/responses.js";

export interface ToolDefinition<TArgs = unknown, TResult = unknown> {
  name: string;
  description: string;
  // JSON schema handed to the OpenAI Responses API.
  parameters: Record<string, unknown>;
  // Zod schema used to validate arguments generated by the model before execution.
  schema: z.ZodType<TArgs>;
  execute: (args: TArgs) => Promise<TResult>;
}

// The registry stores heterogeneous tool definitions, so their arg/result types are erased.
export type AnyToolDefinition = ToolDefinition<any, any>;

export interface ToolRegistry {
  register(tool: AnyToolDefinition): void;
  // Safe lookup: returns undefined if the tool isn't registered.
  get(name: string): AnyToolDefinition | undefined;
  // Strict lookup: throws ToolNotFoundError if the tool isn't registered.
  resolve(name: string): AnyToolDefinition;
  getDefinitions(): FunctionTool[];
}
